name: Core Engine CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-rust-core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install latest stable Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Run Cargo Tests
      working-directory: ./packages/guessrank-core
      run: cargo test --verbose
